name: CI Build & Push to GCP Artifact registry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  GAR_LOCATION: europe-central2-docker.pkg.dev
  PROJECT_ID: seraphic-hawk-505119-h3
  REPOSITORY: devops-app-repo
  IMAGE_NAME: devops-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_LOCATION }}
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: app/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
